<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="BD2KGeneExpression"
    errors="0" failures="1" hostname="" id="" package="BD2KGeneExpression" skipped="0"
    tests="1" time="0.000" timestamp="Thu, 05 Nov 2015 19:23:07 GMT">
  
    <testcase name="BD2KGeneExpression upload and other stuff" time="43.54" assertions="71">

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

      <failure message="Timed out while waiting for element &lt;.panel-danger&gt; to be present for 15000 milliseconds.">    at Object.module.exports.BD2KGeneExpression upload and other stuff (/Users/mokolodi1/work/medbook/wrangler/webapp/tests/nightwatch/walkthroughs/BD2KGeneExpression.js:81:8)
    at Module.call (/usr/local/lib/node_modules/starrynight/node_modules/nightwatch/lib/runner/module.js:60:34)
    at suite.beforeEach.then.then.self.results (/usr/local/lib/node_modules/starrynight/node_modules/nightwatch/lib/runner/testcase.js:96:29)
    at _fulfilled (/usr/local/lib/node_modules/starrynight/node_modules/nightwatch/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/starrynight/node_modules/nightwatch/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/starrynight/node_modules/nightwatch/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/starrynight/node_modules/nightwatch/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/starrynight/node_modules/nightwatch/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/starrynight/node_modules/nightwatch/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:419:13)</failure>

    
    </testcase>
  
  
  </testsuite>
</testsuites>
